function [state_dot] = Physics(rocket, state, control, env)
%%%%% Physics engine that determines state derivatives
%%% Inputs:
%%% Rocket struct
%%% State vector 
%%% Control vector
%%% Environment struct

% state vector:
% position, velocity, q, omega, T, m, cg, cp

% control vector:
% throttle, gimbal angles, fin angles

% env vector:
% g, rho, T, windspeed



%% Logging Rocket Physical Parameteres to improve compute
% rocket = struct( ...
%     'mass', 1, ...
%     'cg', zeros(3,1), ...
%     'I', zeros(3,3), ... %% Intertia tensor
%     'Cl', 0.2, ...
%     'Cd', 1.3, ...
%     'cp', zeros(3,1), ...
%     'T_poa', zeros(3,1), ... %% Thrust point of action
%     'T_max', 100, ...
%     'T_timeconst', 1.2, ...
%     'fin_delay', 0.05, ...
%     'S_ref', 0.1, ...
%     'S_fin', 0.01);
% sim = struct( ...
%     'dt', 1e-5, ...
%     'Integrator', 'ExplicitEuler', ... %% lol
%     'call_steps', 1e3);
% state = struct( ...
%     'position', zeros(3,1), ...
%     'velocity', zeros(3,1), ...
%     'omega', zeros(3,1), ...
%     'q', [1; 0; 0; 0], ... %% Quaternion
%     'T', 0);
% control = struct( ...
%     'throttle', 0, ...
%     'gimbal_pitch', 0, ...
%     'gimbal_yaw', 0, ...
%     'fin', 0);
% env = struct( ...
%     'g', -9.81, ...
%     'temp', 288, ...
%     'rho', 1.225, ...
%     'wind', zeros(3,1));

% Unpacking state struct
x = [state.position,
    state.velocity,
    state.q,
    state.omega,
    state.T,
    state.m,
    state.cg,
    state.cp];

% Computing aero forces


end