function [] = DirSetup()
%%%%% Loads all directories

addpath(fullfile(pwd, 'Config'), ...
        ...
        fullfile(pwd, 'Config/Fits'), ...
        fullfile(pwd, 'Config/Fits/CG'), ...
        fullfile(pwd, 'Config/Fits/CP'), ...
        fullfile(pwd, 'Config/Fits/Geometry'), ...
        fullfile(pwd, 'Config/Fits/Gimbal'), ...
        fullfile(pwd, 'Config/Fits/Inertia'), ...
        fullfile(pwd, 'Config/Fits/Polars'), ...
        fullfile(pwd, 'Config/Fits/Polars/Body'), ...
        fullfile(pwd, 'Config/Fits/Polars/Fins'), ...
        fullfile(pwd, 'Config/Fits/spImpulse'), ...
        fullfile(pwd, 'Config/Fits/Thrust'), ...
        fullfile(pwd, 'Config/Fits/Thrust/Delays'), ...
        fullfile(pwd, 'Config/Fits/Thrust/ThrottleMaps'), ...
        ...
        fullfile(pwd, 'Config/Rocket'), ...
        ...
        fullfile(pwd, 'Controllers'), ...
        ...
        fullfile(pwd, 'Environment'), ...
        ...
        fullfile(pwd, 'Simulation'), ...
        fullfile(pwd, 'Simulation/Engines'), ...
        fullfile(pwd, 'Simulation/PathGen'), ...
        fullfile(pwd, 'Simulation/Integrators'), ...
        fullfile(pwd, 'Simulation/Output'), ...
        fullfile(pwd, 'Simulation/TestModes/'));
end